// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: booking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    hotel_id, guest_id, code, status, 
    room_amount, extras_amount, total_amount, currency
) VALUES (
    $1, $2, $3, $4, 
    $5, $6, $7, $8
)
RETURNING id, created_at
`

type CreateBookingParams struct {
	HotelID      pgtype.UUID    `json:"hotel_id"`
	GuestID      pgtype.UUID    `json:"guest_id"`
	Code         string         `json:"code"`
	Status       pgtype.Text    `json:"status"`
	RoomAmount   pgtype.Numeric `json:"room_amount"`
	ExtrasAmount pgtype.Numeric `json:"extras_amount"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
	Currency     pgtype.Text    `json:"currency"`
}

type CreateBookingRow struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.HotelID,
		arg.GuestID,
		arg.Code,
		arg.Status,
		arg.RoomAmount,
		arg.ExtrasAmount,
		arg.TotalAmount,
		arg.Currency,
	)
	var i CreateBookingRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createBookingRoom = `-- name: CreateBookingRoom :exec
INSERT INTO booking_rooms (
    booking_id, room_type_id, rate_plan_id, 
    check_in, check_out, price_per_night, guest_names
) VALUES (
    $1, $2, $3, 
    $4, $5, $6, $7
)
`

type CreateBookingRoomParams struct {
	BookingID     pgtype.UUID    `json:"booking_id"`
	RoomTypeID    pgtype.UUID    `json:"room_type_id"`
	RatePlanID    pgtype.UUID    `json:"rate_plan_id"`
	CheckIn       pgtype.Date    `json:"check_in"`
	CheckOut      pgtype.Date    `json:"check_out"`
	PricePerNight pgtype.Numeric `json:"price_per_night"`
	GuestNames    []string       `json:"guest_names"`
}

func (q *Queries) CreateBookingRoom(ctx context.Context, arg CreateBookingRoomParams) error {
	_, err := q.db.Exec(ctx, createBookingRoom,
		arg.BookingID,
		arg.RoomTypeID,
		arg.RatePlanID,
		arg.CheckIn,
		arg.CheckOut,
		arg.PricePerNight,
		arg.GuestNames,
	)
	return err
}
