// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guest.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGuest = `-- name: CreateGuest :one
INSERT INTO guests (
    hotel_id, email, full_name, phone
) VALUES (
    $1, $2, $3, $4
)
RETURNING id
`

type CreateGuestParams struct {
	HotelID  pgtype.UUID `json:"hotel_id"`
	Email    pgtype.Text `json:"email"`
	FullName string      `json:"full_name"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) CreateGuest(ctx context.Context, arg CreateGuestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGuest,
		arg.HotelID,
		arg.Email,
		arg.FullName,
		arg.Phone,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
