// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hotel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createHotel = `-- name: CreateHotel :one
INSERT INTO hotels (name, subdomain, currency, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateHotelParams struct {
	Name      string      `json:"name"`
	Subdomain string      `json:"subdomain"`
	Currency  pgtype.Text `json:"currency"`
	OwnerID   pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateHotel(ctx context.Context, arg CreateHotelParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createHotel,
		arg.Name,
		arg.Subdomain,
		arg.Currency,
		arg.OwnerID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listHotelsByOwner = `-- name: ListHotelsByOwner :many
SELECT id, name, subdomain, currency, timezone, settings, created_at, updated_at, owner_id FROM hotels WHERE owner_id = $1
`

func (q *Queries) ListHotelsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Hotel, error) {
	rows, err := q.db.Query(ctx, listHotelsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hotel
	for rows.Next() {
		var i Hotel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Subdomain,
			&i.Currency,
			&i.Timezone,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
