// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInventoryByDateRange = `-- name: GetInventoryByDateRange :many
SELECT 
    id,
    hotel_id,
    room_type_id,
    date,
    total_inventory,
    booked_count,
    price,
    version
FROM inventory
WHERE 
    date >= $1 AND date < $2
ORDER BY date ASC
`

type GetInventoryByDateRangeParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

type GetInventoryByDateRangeRow struct {
	ID             pgtype.UUID    `json:"id"`
	HotelID        pgtype.UUID    `json:"hotel_id"`
	RoomTypeID     pgtype.UUID    `json:"room_type_id"`
	Date           pgtype.Date    `json:"date"`
	TotalInventory int32          `json:"total_inventory"`
	BookedCount    pgtype.Int4    `json:"booked_count"`
	Price          pgtype.Numeric `json:"price"`
	Version        pgtype.Int8    `json:"version"`
}

func (q *Queries) GetInventoryByDateRange(ctx context.Context, arg GetInventoryByDateRangeParams) ([]GetInventoryByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, getInventoryByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryByDateRangeRow
	for rows.Next() {
		var i GetInventoryByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.HotelID,
			&i.RoomTypeID,
			&i.Date,
			&i.TotalInventory,
			&i.BookedCount,
			&i.Price,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreInventory = `-- name: RestoreInventory :exec
UPDATE inventory
SET booked_count = booked_count - 1
WHERE 
    room_type_id = $1
    AND date >= $2::date 
    AND date < $3::date
    AND booked_count > 0
`

type RestoreInventoryParams struct {
	RoomTypeID pgtype.UUID `json:"room_type_id"`
	CheckIn    pgtype.Date `json:"check_in"`
	CheckOut   pgtype.Date `json:"check_out"`
}

func (q *Queries) RestoreInventory(ctx context.Context, arg RestoreInventoryParams) error {
	_, err := q.db.Exec(ctx, restoreInventory, arg.RoomTypeID, arg.CheckIn, arg.CheckOut)
	return err
}

const updateInventoryCount = `-- name: UpdateInventoryCount :one
UPDATE inventory
SET 
    booked_count = booked_count + $3::int,
    version = version + 1
WHERE 
    id = $1 
    AND version = $2
    AND (booked_count + $3::int) <= total_inventory
RETURNING id, version, booked_count
`

type UpdateInventoryCountParams struct {
	ID       pgtype.UUID `json:"id"`
	Version  pgtype.Int8 `json:"version"`
	Quantity int32       `json:"quantity"`
}

type UpdateInventoryCountRow struct {
	ID          pgtype.UUID `json:"id"`
	Version     pgtype.Int8 `json:"version"`
	BookedCount pgtype.Int4 `json:"booked_count"`
}

func (q *Queries) UpdateInventoryCount(ctx context.Context, arg UpdateInventoryCountParams) (UpdateInventoryCountRow, error) {
	row := q.db.QueryRow(ctx, updateInventoryCount, arg.ID, arg.Version, arg.Quantity)
	var i UpdateInventoryCountRow
	err := row.Scan(&i.ID, &i.Version, &i.BookedCount)
	return i, err
}
