// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackupGuestsV2 struct {
	ID             pgtype.UUID        `json:"id"`
	HotelID        pgtype.UUID        `json:"hotel_id"`
	Email          pgtype.Text        `json:"email"`
	FullName       string             `json:"full_name"`
	Phone          pgtype.Text        `json:"phone"`
	PassportNumber pgtype.Text        `json:"passport_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Booking struct {
	ID           pgtype.UUID        `json:"id"`
	HotelID      pgtype.UUID        `json:"hotel_id"`
	GuestID      pgtype.UUID        `json:"guest_id"`
	Code         string             `json:"code"`
	Status       pgtype.Text        `json:"status"`
	RoomAmount   pgtype.Numeric     `json:"room_amount"`
	ExtrasAmount pgtype.Numeric     `json:"extras_amount"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	Currency     pgtype.Text        `json:"currency"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BookingExtra struct {
	ID            pgtype.UUID    `json:"id"`
	BookingID     pgtype.UUID    `json:"booking_id"`
	ExtraID       pgtype.UUID    `json:"extra_id"`
	Quantity      int32          `json:"quantity"`
	UnitPrice     pgtype.Numeric `json:"unit_price"`
	TotalPrice    pgtype.Numeric `json:"total_price"`
	EffectiveDate pgtype.Date    `json:"effective_date"`
}

type BookingRoom struct {
	ID             pgtype.UUID    `json:"id"`
	BookingID      pgtype.UUID    `json:"booking_id"`
	RoomTypeID     pgtype.UUID    `json:"room_type_id"`
	RatePlanID     pgtype.UUID    `json:"rate_plan_id"`
	CheckIn        pgtype.Date    `json:"check_in"`
	CheckOut       pgtype.Date    `json:"check_out"`
	PricePerNight  pgtype.Numeric `json:"price_per_night"`
	AssignedRoomID pgtype.UUID    `json:"assigned_room_id"`
	GuestNames     []string       `json:"guest_names"`
}

type Extra struct {
	ID           pgtype.UUID    `json:"id"`
	HotelID      pgtype.UUID    `json:"hotel_id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	PricingModel string         `json:"pricing_model"`
	Price        pgtype.Numeric `json:"price"`
	Active       pgtype.Bool    `json:"active"`
}

type Guest struct {
	ID             pgtype.UUID        `json:"id"`
	HotelID        pgtype.UUID        `json:"hotel_id"`
	Email          pgtype.Text        `json:"email"`
	FullName       string             `json:"full_name"`
	Phone          pgtype.Text        `json:"phone"`
	PassportNumber pgtype.Text        `json:"passport_number"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Hotel struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Subdomain string             `json:"subdomain"`
	Currency  pgtype.Text        `json:"currency"`
	Timezone  pgtype.Text        `json:"timezone"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Inventory struct {
	ID             pgtype.UUID    `json:"id"`
	HotelID        pgtype.UUID    `json:"hotel_id"`
	RoomTypeID     pgtype.UUID    `json:"room_type_id"`
	RatePlanID     pgtype.UUID    `json:"rate_plan_id"`
	Date           pgtype.Date    `json:"date"`
	TotalInventory int32          `json:"total_inventory"`
	BookedCount    pgtype.Int4    `json:"booked_count"`
	HoldCount      pgtype.Int4    `json:"hold_count"`
	Price          pgtype.Numeric `json:"price"`
	IsClosed       pgtype.Bool    `json:"is_closed"`
	MinStay        pgtype.Int4    `json:"min_stay"`
	Version        pgtype.Int8    `json:"version"`
}

type RatePlan struct {
	ID              pgtype.UUID `json:"id"`
	HotelID         pgtype.UUID `json:"hotel_id"`
	Name            string      `json:"name"`
	IsNonRefundable pgtype.Bool `json:"is_non_refundable"`
	MealsIncluded   pgtype.Text `json:"meals_included"`
	Active          pgtype.Bool `json:"active"`
}

type Room struct {
	ID         pgtype.UUID `json:"id"`
	HotelID    pgtype.UUID `json:"hotel_id"`
	RoomTypeID pgtype.UUID `json:"room_type_id"`
	Number     string      `json:"number"`
	Floor      pgtype.Int4 `json:"floor"`
	Status     pgtype.Text `json:"status"`
}

type RoomType struct {
	ID           pgtype.UUID    `json:"id"`
	HotelID      pgtype.UUID    `json:"hotel_id"`
	Name         string         `json:"name"`
	Code         pgtype.Text    `json:"code"`
	MaxOccupancy int32          `json:"max_occupancy"`
	BasePrice    pgtype.Numeric `json:"base_price"`
	Amenities    []byte         `json:"amenities"`
	Description  pgtype.Text    `json:"description"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	HotelID      pgtype.UUID        `json:"hotel_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
