// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (CreateBookingRow, error)
	CreateBookingRoom(ctx context.Context, arg CreateBookingRoomParams) error
	CreateGuest(ctx context.Context, arg CreateGuestParams) (pgtype.UUID, error)
	CreateHotel(ctx context.Context, arg CreateHotelParams) (pgtype.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	GetBookingByID(ctx context.Context, id pgtype.UUID) (GetBookingByIDRow, error)
	GetBookingRooms(ctx context.Context, bookingID pgtype.UUID) ([]BookingRoom, error)
	GetInventoryByDateRange(ctx context.Context, arg GetInventoryByDateRangeParams) ([]GetInventoryByDateRangeRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]ListBookingsRow, error)
	ListHotelsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Hotel, error)
	RestoreInventory(ctx context.Context, arg RestoreInventoryParams) error
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpdateInventoryCount(ctx context.Context, arg UpdateInventoryCountParams) (UpdateInventoryCountRow, error)
}

var _ Querier = (*Queries)(nil)
